name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
# TODO: use https://github.com/actions/deploy-pages
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

#       - name: Deploy Mkdocs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 6.x
            
      - name: Setup Docfx
        run: dotnet tool install -g docfx
      - name: Build
        run: docfx AnitomySharp/docfx_project/docfx.json

      - name: Deploy Docfx
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: AnitomySharp/docfx_project/_site
            keep_files: true
