name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: AnitomySharp-artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: AnitomySharp/bin/Debug/net6.0/AnitomySharp.dll
        if-no-files-found: error
        retention-days: 30

    - name: publish on version change
      id: publish_nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: AnitomySharp/AnitomySharp.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: release-please
      uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: simple
    - name: Upload Release Artifact
      if: ${{ steps.release.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:
        gh release upload ${{ steps.release.outputs.tag_name }} ./artifact/AnitomySharp-artifact.zip